apiVersion: v1
kind: Service
metadata:
  name: recurso-api
  namespace: recurso
  labels:
    app: recurso
    component: api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: recurso
    component: api
