ALTER TABLE customers DROP COLUMN IF EXISTS phone;
ALTER TABLE customers DROP COLUMN IF EXISTS tax_id;
ALTER TABLE customers DROP COLUMN IF EXISTS line1;
ALTER TABLE customers DROP COLUMN IF EXISTS city;
ALTER TABLE customers DROP COLUMN IF EXISTS state;
ALTER TABLE customers DROP COLUMN IF EXISTS zip;
ALTER TABLE customers DROP COLUMN IF EXISTS country;
