// Code generated by porttest/gen; DO NOT EDIT.

package porttest

import (
	"context"
	"github.com/google/uuid"
	"github.com/recurso-dev/recurso/internal/core/domain"
	"github.com/recurso-dev/recurso/internal/core/port"
	"time"
)

// UnimplementedAccountingConnectionRepository panics on every AccountingConnectionRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedAccountingConnectionRepository struct{}

var _ port.AccountingConnectionRepository = UnimplementedAccountingConnectionRepository{}

func (UnimplementedAccountingConnectionRepository) Create(context.Context, *domain.AccountingConnection) error {
	panic("porttest: AccountingConnectionRepository.Create is not implemented")
}

func (UnimplementedAccountingConnectionRepository) GetByID(context.Context, uuid.UUID) (*domain.AccountingConnection, error) {
	panic("porttest: AccountingConnectionRepository.GetByID is not implemented")
}

func (UnimplementedAccountingConnectionRepository) GetByTenantAndProvider(context.Context, uuid.UUID, string) (*domain.AccountingConnection, error) {
	panic("porttest: AccountingConnectionRepository.GetByTenantAndProvider is not implemented")
}

func (UnimplementedAccountingConnectionRepository) ListByTenant(context.Context, uuid.UUID) ([]*domain.AccountingConnection, error) {
	panic("porttest: AccountingConnectionRepository.ListByTenant is not implemented")
}

func (UnimplementedAccountingConnectionRepository) Update(context.Context, *domain.AccountingConnection) error {
	panic("porttest: AccountingConnectionRepository.Update is not implemented")
}

func (UnimplementedAccountingConnectionRepository) Delete(context.Context, uuid.UUID) error {
	panic("porttest: AccountingConnectionRepository.Delete is not implemented")
}

func (UnimplementedAccountingConnectionRepository) GetActiveConnections(context.Context) ([]*domain.AccountingConnection, error) {
	panic("porttest: AccountingConnectionRepository.GetActiveConnections is not implemented")
}

func (UnimplementedAccountingConnectionRepository) CreateSyncLog(context.Context, *domain.AccountingSyncLog) error {
	panic("porttest: AccountingConnectionRepository.CreateSyncLog is not implemented")
}

func (UnimplementedAccountingConnectionRepository) ListSyncLogs(context.Context, uuid.UUID, int) ([]*domain.AccountingSyncLog, error) {
	panic("porttest: AccountingConnectionRepository.ListSyncLogs is not implemented")
}

// UnimplementedAccountingGateway panics on every AccountingGateway method; embed it and override the
// methods the code under test actually calls.
type UnimplementedAccountingGateway struct{}

var _ port.AccountingGateway = UnimplementedAccountingGateway{}

func (UnimplementedAccountingGateway) SyncCustomer(context.Context, *domain.Customer, string) (string, error) {
	panic("porttest: AccountingGateway.SyncCustomer is not implemented")
}

func (UnimplementedAccountingGateway) SyncInvoice(context.Context, *domain.Invoice, port.InvoiceSyncRefs, string) (string, error) {
	panic("porttest: AccountingGateway.SyncInvoice is not implemented")
}

func (UnimplementedAccountingGateway) SyncProduct(context.Context, *domain.Plan, string) (string, error) {
	panic("porttest: AccountingGateway.SyncProduct is not implemented")
}

// UnimplementedAccountingMappingRepository panics on every AccountingMappingRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedAccountingMappingRepository struct{}

var _ port.AccountingMappingRepository = UnimplementedAccountingMappingRepository{}

func (UnimplementedAccountingMappingRepository) Upsert(context.Context, *domain.AccountingEntityMapping) error {
	panic("porttest: AccountingMappingRepository.Upsert is not implemented")
}

func (UnimplementedAccountingMappingRepository) Get(context.Context, uuid.UUID, string, uuid.UUID) (*domain.AccountingEntityMapping, error) {
	panic("porttest: AccountingMappingRepository.Get is not implemented")
}

func (UnimplementedAccountingMappingRepository) Delete(context.Context, uuid.UUID, string, uuid.UUID) error {
	panic("porttest: AccountingMappingRepository.Delete is not implemented")
}

// UnimplementedAccountingService panics on every AccountingService method; embed it and override the
// methods the code under test actually calls.
type UnimplementedAccountingService struct{}

var _ port.AccountingService = UnimplementedAccountingService{}

func (UnimplementedAccountingService) SyncCustomer(context.Context, uuid.UUID) error {
	panic("porttest: AccountingService.SyncCustomer is not implemented")
}

func (UnimplementedAccountingService) SyncInvoice(context.Context, uuid.UUID) error {
	panic("porttest: AccountingService.SyncInvoice is not implemented")
}

func (UnimplementedAccountingService) SyncProduct(context.Context, string) error {
	panic("porttest: AccountingService.SyncProduct is not implemented")
}

func (UnimplementedAccountingService) SyncAllForTenant(context.Context, uuid.UUID, bool) error {
	panic("porttest: AccountingService.SyncAllForTenant is not implemented")
}

// UnimplementedAuditLogRepository panics on every AuditLogRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedAuditLogRepository struct{}

var _ port.AuditLogRepository = UnimplementedAuditLogRepository{}

func (UnimplementedAuditLogRepository) Insert(context.Context, *domain.AuditLog) error {
	panic("porttest: AuditLogRepository.Insert is not implemented")
}

func (UnimplementedAuditLogRepository) List(context.Context, uuid.UUID, domain.AuditLogFilter) ([]domain.AuditLog, error) {
	panic("porttest: AuditLogRepository.List is not implemented")
}

// UnimplementedBillableMetricRepository panics on every BillableMetricRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedBillableMetricRepository struct{}

var _ port.BillableMetricRepository = UnimplementedBillableMetricRepository{}

func (UnimplementedBillableMetricRepository) Create(context.Context, *domain.BillableMetric) error {
	panic("porttest: BillableMetricRepository.Create is not implemented")
}

func (UnimplementedBillableMetricRepository) GetByID(context.Context, uuid.UUID, uuid.UUID) (*domain.BillableMetric, error) {
	panic("porttest: BillableMetricRepository.GetByID is not implemented")
}

func (UnimplementedBillableMetricRepository) GetByCode(context.Context, uuid.UUID, string) (*domain.BillableMetric, error) {
	panic("porttest: BillableMetricRepository.GetByCode is not implemented")
}

func (UnimplementedBillableMetricRepository) ListByTenant(context.Context, uuid.UUID) ([]domain.BillableMetric, error) {
	panic("porttest: BillableMetricRepository.ListByTenant is not implemented")
}

func (UnimplementedBillableMetricRepository) Update(context.Context, *domain.BillableMetric) error {
	panic("porttest: BillableMetricRepository.Update is not implemented")
}

func (UnimplementedBillableMetricRepository) Delete(context.Context, uuid.UUID, uuid.UUID) error {
	panic("porttest: BillableMetricRepository.Delete is not implemented")
}

// UnimplementedCancelFlowRepository panics on every CancelFlowRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedCancelFlowRepository struct{}

var _ port.CancelFlowRepository = UnimplementedCancelFlowRepository{}

func (UnimplementedCancelFlowRepository) CreateFlow(context.Context, *domain.CancelFlow) error {
	panic("porttest: CancelFlowRepository.CreateFlow is not implemented")
}

func (UnimplementedCancelFlowRepository) GetFlowByID(context.Context, uuid.UUID) (*domain.CancelFlow, error) {
	panic("porttest: CancelFlowRepository.GetFlowByID is not implemented")
}

func (UnimplementedCancelFlowRepository) GetDefaultFlowForTenant(context.Context, uuid.UUID) (*domain.CancelFlow, error) {
	panic("porttest: CancelFlowRepository.GetDefaultFlowForTenant is not implemented")
}

func (UnimplementedCancelFlowRepository) ListFlowsByTenant(context.Context, uuid.UUID) ([]*domain.CancelFlow, error) {
	panic("porttest: CancelFlowRepository.ListFlowsByTenant is not implemented")
}

func (UnimplementedCancelFlowRepository) UpdateFlow(context.Context, *domain.CancelFlow) error {
	panic("porttest: CancelFlowRepository.UpdateFlow is not implemented")
}

func (UnimplementedCancelFlowRepository) CreateStep(context.Context, *domain.CancelFlowStep) error {
	panic("porttest: CancelFlowRepository.CreateStep is not implemented")
}

func (UnimplementedCancelFlowRepository) GetStepsByFlow(context.Context, uuid.UUID) ([]domain.CancelFlowStep, error) {
	panic("porttest: CancelFlowRepository.GetStepsByFlow is not implemented")
}

func (UnimplementedCancelFlowRepository) UpdateStep(context.Context, *domain.CancelFlowStep, uuid.UUID) error {
	panic("porttest: CancelFlowRepository.UpdateStep is not implemented")
}

func (UnimplementedCancelFlowRepository) DeleteStep(context.Context, uuid.UUID, uuid.UUID) error {
	panic("porttest: CancelFlowRepository.DeleteStep is not implemented")
}

func (UnimplementedCancelFlowRepository) CreateSession(context.Context, *domain.CancelFlowSession) error {
	panic("porttest: CancelFlowRepository.CreateSession is not implemented")
}

func (UnimplementedCancelFlowRepository) GetSessionByID(context.Context, uuid.UUID) (*domain.CancelFlowSession, error) {
	panic("porttest: CancelFlowRepository.GetSessionByID is not implemented")
}

func (UnimplementedCancelFlowRepository) UpdateSession(context.Context, *domain.CancelFlowSession) error {
	panic("porttest: CancelFlowRepository.UpdateSession is not implemented")
}

func (UnimplementedCancelFlowRepository) GetRecentSessionByCustomer(context.Context, uuid.UUID) (*domain.CancelFlowSession, error) {
	panic("porttest: CancelFlowRepository.GetRecentSessionByCustomer is not implemented")
}

func (UnimplementedCancelFlowRepository) ClaimStep(context.Context, uuid.UUID, uuid.UUID, int) (bool, error) {
	panic("porttest: CancelFlowRepository.ClaimStep is not implemented")
}

func (UnimplementedCancelFlowRepository) GetSessionStats(context.Context, uuid.UUID, uuid.UUID) (*domain.FlowStats, error) {
	panic("porttest: CancelFlowRepository.GetSessionStats is not implemented")
}

// UnimplementedCardVault panics on every CardVault method; embed it and override the
// methods the code under test actually calls.
type UnimplementedCardVault struct{}

var _ port.CardVault = UnimplementedCardVault{}

func (UnimplementedCardVault) Tokenize(context.Context, string, string, string, string) (*port.CardToken, error) {
	panic("porttest: CardVault.Tokenize is not implemented")
}

func (UnimplementedCardVault) Detokenize(context.Context, string) (*port.CardToken, error) {
	panic("porttest: CardVault.Detokenize is not implemented")
}

func (UnimplementedCardVault) DeleteToken(context.Context, string) error {
	panic("porttest: CardVault.DeleteToken is not implemented")
}

func (UnimplementedCardVault) GetByFingerprint(context.Context, string) (*port.CardToken, error) {
	panic("porttest: CardVault.GetByFingerprint is not implemented")
}

// UnimplementedChargeRepository panics on every ChargeRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedChargeRepository struct{}

var _ port.ChargeRepository = UnimplementedChargeRepository{}

func (UnimplementedChargeRepository) ReplaceForPlan(context.Context, uuid.UUID, uuid.UUID, []domain.Charge) error {
	panic("porttest: ChargeRepository.ReplaceForPlan is not implemented")
}

func (UnimplementedChargeRepository) ListByPlan(context.Context, uuid.UUID, uuid.UUID) ([]domain.Charge, error) {
	panic("porttest: ChargeRepository.ListByPlan is not implemented")
}

func (UnimplementedChargeRepository) ListByMetric(context.Context, uuid.UUID, uuid.UUID) ([]domain.MetricPlanCharge, error) {
	panic("porttest: ChargeRepository.ListByMetric is not implemented")
}

// UnimplementedCouponRepository panics on every CouponRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedCouponRepository struct{}

var _ port.CouponRepository = UnimplementedCouponRepository{}

func (UnimplementedCouponRepository) Create(context.Context, *domain.Coupon) error {
	panic("porttest: CouponRepository.Create is not implemented")
}

func (UnimplementedCouponRepository) GetByCode(context.Context, uuid.UUID, string) (*domain.Coupon, error) {
	panic("porttest: CouponRepository.GetByCode is not implemented")
}

func (UnimplementedCouponRepository) GetByID(context.Context, uuid.UUID, uuid.UUID) (*domain.Coupon, error) {
	panic("porttest: CouponRepository.GetByID is not implemented")
}

func (UnimplementedCouponRepository) List(context.Context, uuid.UUID, int, int) ([]*domain.Coupon, error) {
	panic("porttest: CouponRepository.List is not implemented")
}

// UnimplementedCustomerRepository panics on every CustomerRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedCustomerRepository struct{}

var _ port.CustomerRepository = UnimplementedCustomerRepository{}

func (UnimplementedCustomerRepository) Create(context.Context, *domain.Customer) error {
	panic("porttest: CustomerRepository.Create is not implemented")
}

func (UnimplementedCustomerRepository) GetByID(context.Context, uuid.UUID) (*domain.Customer, error) {
	panic("porttest: CustomerRepository.GetByID is not implemented")
}

func (UnimplementedCustomerRepository) GetByIDPublic(context.Context, uuid.UUID) (*domain.Customer, error) {
	panic("porttest: CustomerRepository.GetByIDPublic is not implemented")
}

func (UnimplementedCustomerRepository) GetByReferralCode(context.Context, uuid.UUID, string) (*domain.Customer, error) {
	panic("porttest: CustomerRepository.GetByReferralCode is not implemented")
}

func (UnimplementedCustomerRepository) List(context.Context, uuid.UUID, domain.CustomerFilter) ([]*domain.Customer, error) {
	panic("porttest: CustomerRepository.List is not implemented")
}

func (UnimplementedCustomerRepository) FindByEmailAcrossTenants(context.Context, string) ([]*domain.Customer, error) {
	panic("porttest: CustomerRepository.FindByEmailAcrossTenants is not implemented")
}

func (UnimplementedCustomerRepository) Update(context.Context, *domain.Customer) error {
	panic("porttest: CustomerRepository.Update is not implemented")
}

func (UnimplementedCustomerRepository) UpdateRisk(context.Context, uuid.UUID, int, map[string]interface{}) error {
	panic("porttest: CustomerRepository.UpdateRisk is not implemented")
}

func (UnimplementedCustomerRepository) UpdatePaymentMethod(context.Context, uuid.UUID, string, string, int, int) error {
	panic("porttest: CustomerRepository.UpdatePaymentMethod is not implemented")
}

// UnimplementedDisputeRepository panics on every DisputeRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedDisputeRepository struct{}

var _ port.DisputeRepository = UnimplementedDisputeRepository{}

func (UnimplementedDisputeRepository) Create(context.Context, *domain.InvoiceDispute) error {
	panic("porttest: DisputeRepository.Create is not implemented")
}

func (UnimplementedDisputeRepository) GetByID(context.Context, uuid.UUID) (*domain.InvoiceDispute, error) {
	panic("porttest: DisputeRepository.GetByID is not implemented")
}

func (UnimplementedDisputeRepository) GetOpenByInvoiceID(context.Context, uuid.UUID) (*domain.InvoiceDispute, error) {
	panic("porttest: DisputeRepository.GetOpenByInvoiceID is not implemented")
}

func (UnimplementedDisputeRepository) UpdateReason(context.Context, uuid.UUID, uuid.UUID, string) error {
	panic("porttest: DisputeRepository.UpdateReason is not implemented")
}

func (UnimplementedDisputeRepository) ListByCustomerID(context.Context, uuid.UUID) ([]*domain.InvoiceDispute, error) {
	panic("porttest: DisputeRepository.ListByCustomerID is not implemented")
}

func (UnimplementedDisputeRepository) ListByCustomerIDPaged(context.Context, uuid.UUID, int, int) ([]*domain.InvoiceDispute, error) {
	panic("porttest: DisputeRepository.ListByCustomerIDPaged is not implemented")
}

func (UnimplementedDisputeRepository) ListByTenant(context.Context, uuid.UUID, string, int, int) ([]*domain.InvoiceDispute, error) {
	panic("porttest: DisputeRepository.ListByTenant is not implemented")
}

func (UnimplementedDisputeRepository) Resolve(context.Context, uuid.UUID, uuid.UUID, string) error {
	panic("porttest: DisputeRepository.Resolve is not implemented")
}

func (UnimplementedDisputeRepository) Close(context.Context, uuid.UUID, uuid.UUID, domain.DisputeStatus, string) error {
	panic("porttest: DisputeRepository.Close is not implemented")
}

// UnimplementedDunningCampaignRepository panics on every DunningCampaignRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedDunningCampaignRepository struct{}

var _ port.DunningCampaignRepository = UnimplementedDunningCampaignRepository{}

func (UnimplementedDunningCampaignRepository) CreateCampaign(context.Context, *domain.DunningCampaign) error {
	panic("porttest: DunningCampaignRepository.CreateCampaign is not implemented")
}

func (UnimplementedDunningCampaignRepository) GetCampaignByID(context.Context, uuid.UUID, uuid.UUID) (*domain.DunningCampaign, error) {
	panic("porttest: DunningCampaignRepository.GetCampaignByID is not implemented")
}

func (UnimplementedDunningCampaignRepository) GetActiveCampaignForTenant(context.Context, uuid.UUID, string) (*domain.DunningCampaign, error) {
	panic("porttest: DunningCampaignRepository.GetActiveCampaignForTenant is not implemented")
}

func (UnimplementedDunningCampaignRepository) ListCampaignsByTenant(context.Context, uuid.UUID) ([]*domain.DunningCampaign, error) {
	panic("porttest: DunningCampaignRepository.ListCampaignsByTenant is not implemented")
}

func (UnimplementedDunningCampaignRepository) UpdateCampaign(context.Context, *domain.DunningCampaign) error {
	panic("porttest: DunningCampaignRepository.UpdateCampaign is not implemented")
}

func (UnimplementedDunningCampaignRepository) CreateStep(context.Context, *domain.DunningCampaignStep, uuid.UUID) error {
	panic("porttest: DunningCampaignRepository.CreateStep is not implemented")
}

func (UnimplementedDunningCampaignRepository) GetStepsByCampaign(context.Context, uuid.UUID) ([]domain.DunningCampaignStep, error) {
	panic("porttest: DunningCampaignRepository.GetStepsByCampaign is not implemented")
}

func (UnimplementedDunningCampaignRepository) UpdateStep(context.Context, *domain.DunningCampaignStep, uuid.UUID) error {
	panic("porttest: DunningCampaignRepository.UpdateStep is not implemented")
}

func (UnimplementedDunningCampaignRepository) DeleteStep(context.Context, uuid.UUID, uuid.UUID) error {
	panic("porttest: DunningCampaignRepository.DeleteStep is not implemented")
}

func (UnimplementedDunningCampaignRepository) CreateExecution(context.Context, *domain.DunningCampaignExecution) error {
	panic("porttest: DunningCampaignRepository.CreateExecution is not implemented")
}

func (UnimplementedDunningCampaignRepository) GetExecutionByInvoice(context.Context, uuid.UUID) (*domain.DunningCampaignExecution, error) {
	panic("porttest: DunningCampaignRepository.GetExecutionByInvoice is not implemented")
}

func (UnimplementedDunningCampaignRepository) UpdateExecution(context.Context, *domain.DunningCampaignExecution) error {
	panic("porttest: DunningCampaignRepository.UpdateExecution is not implemented")
}

func (UnimplementedDunningCampaignRepository) GetDueExecutions(context.Context, time.Time) ([]*domain.DunningCampaignExecution, error) {
	panic("porttest: DunningCampaignRepository.GetDueExecutions is not implemented")
}

func (UnimplementedDunningCampaignRepository) ClaimDueExecutions(context.Context, time.Time, time.Time, int) ([]*domain.DunningCampaignExecution, error) {
	panic("porttest: DunningCampaignRepository.ClaimDueExecutions is not implemented")
}

// UnimplementedEUInvoiceTransport panics on every EUInvoiceTransport method; embed it and override the
// methods the code under test actually calls.
type UnimplementedEUInvoiceTransport struct{}

var _ port.EUInvoiceTransport = UnimplementedEUInvoiceTransport{}

func (UnimplementedEUInvoiceTransport) Transmit(context.Context, domain.EUInvoiceSyntax, string, []byte) (*domain.EUInvoiceTransmission, error) {
	panic("porttest: EUInvoiceTransport.Transmit is not implemented")
}

// UnimplementedEmailSender panics on every EmailSender method; embed it and override the
// methods the code under test actually calls.
type UnimplementedEmailSender struct{}

var _ port.EmailSender = UnimplementedEmailSender{}

func (UnimplementedEmailSender) Send(context.Context, port.EmailMessage) error {
	panic("porttest: EmailSender.Send is not implemented")
}

// UnimplementedEmailVerificationRepository panics on every EmailVerificationRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedEmailVerificationRepository struct{}

var _ port.EmailVerificationRepository = UnimplementedEmailVerificationRepository{}

func (UnimplementedEmailVerificationRepository) Create(context.Context, *domain.EmailVerificationToken) error {
	panic("porttest: EmailVerificationRepository.Create is not implemented")
}

func (UnimplementedEmailVerificationRepository) GetByTokenHash(context.Context, string) (*domain.EmailVerificationToken, error) {
	panic("porttest: EmailVerificationRepository.GetByTokenHash is not implemented")
}

func (UnimplementedEmailVerificationRepository) MarkUsed(context.Context, uuid.UUID) (bool, error) {
	panic("porttest: EmailVerificationRepository.MarkUsed is not implemented")
}

// UnimplementedEntitlementRepository panics on every EntitlementRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedEntitlementRepository struct{}

var _ port.EntitlementRepository = UnimplementedEntitlementRepository{}

func (UnimplementedEntitlementRepository) ReplaceForPlan(context.Context, uuid.UUID, uuid.UUID, []domain.Entitlement) error {
	panic("porttest: EntitlementRepository.ReplaceForPlan is not implemented")
}

func (UnimplementedEntitlementRepository) ListByPlan(context.Context, uuid.UUID, uuid.UUID) ([]domain.Entitlement, error) {
	panic("porttest: EntitlementRepository.ListByPlan is not implemented")
}

func (UnimplementedEntitlementRepository) ListByPlanIDs(context.Context, uuid.UUID, []uuid.UUID) ([]domain.Entitlement, error) {
	panic("porttest: EntitlementRepository.ListByPlanIDs is not implemented")
}

func (UnimplementedEntitlementRepository) CheckFeature(context.Context, uuid.UUID, uuid.UUID, string) (*domain.EntitlementCheck, error) {
	panic("porttest: EntitlementRepository.CheckFeature is not implemented")
}

// UnimplementedEventDeliveryRepository panics on every EventDeliveryRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedEventDeliveryRepository struct{}

var _ port.EventDeliveryRepository = UnimplementedEventDeliveryRepository{}

func (UnimplementedEventDeliveryRepository) Create(context.Context, *domain.EventDelivery) error {
	panic("porttest: EventDeliveryRepository.Create is not implemented")
}

func (UnimplementedEventDeliveryRepository) Update(context.Context, *domain.EventDelivery) error {
	panic("porttest: EventDeliveryRepository.Update is not implemented")
}

func (UnimplementedEventDeliveryRepository) ListByEventID(context.Context, uuid.UUID) ([]*domain.EventDelivery, error) {
	panic("porttest: EventDeliveryRepository.ListByEventID is not implemented")
}

func (UnimplementedEventDeliveryRepository) ListByEndpointID(context.Context, uuid.UUID, string, int, int) ([]*domain.EventDelivery, error) {
	panic("porttest: EventDeliveryRepository.ListByEndpointID is not implemented")
}

func (UnimplementedEventDeliveryRepository) ListPending(context.Context, int) ([]*domain.EventDelivery, error) {
	panic("porttest: EventDeliveryRepository.ListPending is not implemented")
}

func (UnimplementedEventDeliveryRepository) ClaimPending(context.Context, time.Duration, int) ([]*domain.EventDelivery, error) {
	panic("porttest: EventDeliveryRepository.ClaimPending is not implemented")
}

// UnimplementedEventRepository panics on every EventRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedEventRepository struct{}

var _ port.EventRepository = UnimplementedEventRepository{}

func (UnimplementedEventRepository) Create(context.Context, *domain.Event) error {
	panic("porttest: EventRepository.Create is not implemented")
}

func (UnimplementedEventRepository) GetByID(context.Context, uuid.UUID) (*domain.Event, error) {
	panic("porttest: EventRepository.GetByID is not implemented")
}

func (UnimplementedEventRepository) ListByTenantID(context.Context, uuid.UUID, string, int, int) ([]*domain.Event, error) {
	panic("porttest: EventRepository.ListByTenantID is not implemented")
}

func (UnimplementedEventRepository) ListByObject(context.Context, uuid.UUID, uuid.UUID, int, int) ([]*domain.Event, error) {
	panic("porttest: EventRepository.ListByObject is not implemented")
}

// UnimplementedExchangeRateProvider panics on every ExchangeRateProvider method; embed it and override the
// methods the code under test actually calls.
type UnimplementedExchangeRateProvider struct{}

var _ port.ExchangeRateProvider = UnimplementedExchangeRateProvider{}

func (UnimplementedExchangeRateProvider) GetRate(context.Context, string, string) (float64, error) {
	panic("porttest: ExchangeRateProvider.GetRate is not implemented")
}

func (UnimplementedExchangeRateProvider) Convert(context.Context, int64, string, string) (int64, float64, error) {
	panic("porttest: ExchangeRateProvider.Convert is not implemented")
}

func (UnimplementedExchangeRateProvider) ListRates(context.Context, string) ([]port.ExchangeRate, error) {
	panic("porttest: ExchangeRateProvider.ListRates is not implemented")
}

// UnimplementedGSPAdapter panics on every GSPAdapter method; embed it and override the
// methods the code under test actually calls.
type UnimplementedGSPAdapter struct{}

var _ port.GSPAdapter = UnimplementedGSPAdapter{}

func (UnimplementedGSPAdapter) GenerateIRN(context.Context, *domain.Invoice) (*port.EInvoiceResponse, error) {
	panic("porttest: GSPAdapter.GenerateIRN is not implemented")
}

func (UnimplementedGSPAdapter) GenerateIRNFull(context.Context, *port.EInvoiceRequest) (*port.EInvoiceResponse, error) {
	panic("porttest: GSPAdapter.GenerateIRNFull is not implemented")
}

func (UnimplementedGSPAdapter) CancelIRN(context.Context, string, string) error {
	panic("porttest: GSPAdapter.CancelIRN is not implemented")
}

func (UnimplementedGSPAdapter) GetIRNByDocDetails(context.Context, string, string, string) (*port.EInvoiceResponse, error) {
	panic("porttest: GSPAdapter.GetIRNByDocDetails is not implemented")
}

// UnimplementedGatewayConnectionRepository panics on every GatewayConnectionRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedGatewayConnectionRepository struct{}

var _ port.GatewayConnectionRepository = UnimplementedGatewayConnectionRepository{}

func (UnimplementedGatewayConnectionRepository) Upsert(context.Context, *domain.GatewayConnection) error {
	panic("porttest: GatewayConnectionRepository.Upsert is not implemented")
}

func (UnimplementedGatewayConnectionRepository) GetByID(context.Context, uuid.UUID) (*domain.GatewayConnection, error) {
	panic("porttest: GatewayConnectionRepository.GetByID is not implemented")
}

func (UnimplementedGatewayConnectionRepository) GetActive(context.Context, uuid.UUID, domain.GatewayProvider) (*domain.GatewayConnection, error) {
	panic("porttest: GatewayConnectionRepository.GetActive is not implemented")
}

func (UnimplementedGatewayConnectionRepository) ListByTenant(context.Context, uuid.UUID) ([]*domain.GatewayConnection, error) {
	panic("porttest: GatewayConnectionRepository.ListByTenant is not implemented")
}

func (UnimplementedGatewayConnectionRepository) Deactivate(context.Context, uuid.UUID, domain.GatewayProvider) error {
	panic("porttest: GatewayConnectionRepository.Deactivate is not implemented")
}

func (UnimplementedGatewayConnectionRepository) SetWebhookSecret(context.Context, uuid.UUID, domain.GatewayProvider, string) error {
	panic("porttest: GatewayConnectionRepository.SetWebhookSecret is not implemented")
}

// UnimplementedGiftRepository panics on every GiftRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedGiftRepository struct{}

var _ port.GiftRepository = UnimplementedGiftRepository{}

func (UnimplementedGiftRepository) Create(context.Context, *domain.Gift) error {
	panic("porttest: GiftRepository.Create is not implemented")
}

func (UnimplementedGiftRepository) GetByCode(context.Context, uuid.UUID, string) (*domain.Gift, error) {
	panic("porttest: GiftRepository.GetByCode is not implemented")
}

func (UnimplementedGiftRepository) List(context.Context, uuid.UUID, int, int) ([]*domain.Gift, error) {
	panic("porttest: GiftRepository.List is not implemented")
}

func (UnimplementedGiftRepository) Update(context.Context, *domain.Gift) error {
	panic("porttest: GiftRepository.Update is not implemented")
}

func (UnimplementedGiftRepository) MarkRedeemed(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, time.Time) (bool, error) {
	panic("porttest: GiftRepository.MarkRedeemed is not implemented")
}

func (UnimplementedGiftRepository) GetByID(context.Context, uuid.UUID, uuid.UUID) (*domain.Gift, error) {
	panic("porttest: GiftRepository.GetByID is not implemented")
}

func (UnimplementedGiftRepository) SetInvoiceID(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error {
	panic("porttest: GiftRepository.SetInvoiceID is not implemented")
}

func (UnimplementedGiftRepository) Cancel(context.Context, uuid.UUID, uuid.UUID) (bool, error) {
	panic("porttest: GiftRepository.Cancel is not implemented")
}

func (UnimplementedGiftRepository) RevertRedemption(context.Context, uuid.UUID, uuid.UUID) error {
	panic("porttest: GiftRepository.RevertRedemption is not implemented")
}

// UnimplementedIdempotencyStore panics on every IdempotencyStore method; embed it and override the
// methods the code under test actually calls.
type UnimplementedIdempotencyStore struct{}

var _ port.IdempotencyStore = UnimplementedIdempotencyStore{}

func (UnimplementedIdempotencyStore) Get(context.Context, string) (*domain.StoredResponse, error) {
	panic("porttest: IdempotencyStore.Get is not implemented")
}

func (UnimplementedIdempotencyStore) Set(context.Context, string, *domain.StoredResponse) error {
	panic("porttest: IdempotencyStore.Set is not implemented")
}

func (UnimplementedIdempotencyStore) Claim(context.Context, string) (bool, *domain.StoredResponse, error) {
	panic("porttest: IdempotencyStore.Claim is not implemented")
}

func (UnimplementedIdempotencyStore) Delete(context.Context, string) error {
	panic("porttest: IdempotencyStore.Delete is not implemented")
}

// UnimplementedImportRefRepository panics on every ImportRefRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedImportRefRepository struct{}

var _ port.ImportRefRepository = UnimplementedImportRefRepository{}

func (UnimplementedImportRefRepository) Create(context.Context, *domain.ImportExternalRef) error {
	panic("porttest: ImportRefRepository.Create is not implemented")
}

func (UnimplementedImportRefRepository) ListExternalIDs(context.Context, uuid.UUID, string) (map[string]bool, error) {
	panic("porttest: ImportRefRepository.ListExternalIDs is not implemented")
}

func (UnimplementedImportRefRepository) ListRefs(context.Context, uuid.UUID, string) ([]*domain.ImportExternalRef, error) {
	panic("porttest: ImportRefRepository.ListRefs is not implemented")
}

// UnimplementedIntegrationConnectionRepository panics on every IntegrationConnectionRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedIntegrationConnectionRepository struct{}

var _ port.IntegrationConnectionRepository = UnimplementedIntegrationConnectionRepository{}

func (UnimplementedIntegrationConnectionRepository) Upsert(context.Context, *domain.IntegrationConnection) error {
	panic("porttest: IntegrationConnectionRepository.Upsert is not implemented")
}

func (UnimplementedIntegrationConnectionRepository) GetActive(context.Context, uuid.UUID, domain.IntegrationCategory, string) (*domain.IntegrationConnection, error) {
	panic("porttest: IntegrationConnectionRepository.GetActive is not implemented")
}

func (UnimplementedIntegrationConnectionRepository) ListByTenant(context.Context, uuid.UUID) ([]*domain.IntegrationConnection, error) {
	panic("porttest: IntegrationConnectionRepository.ListByTenant is not implemented")
}

func (UnimplementedIntegrationConnectionRepository) Deactivate(context.Context, uuid.UUID, domain.IntegrationCategory, string) error {
	panic("porttest: IntegrationConnectionRepository.Deactivate is not implemented")
}

// UnimplementedInvoiceItemRepository panics on every InvoiceItemRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedInvoiceItemRepository struct{}

var _ port.InvoiceItemRepository = UnimplementedInvoiceItemRepository{}

func (UnimplementedInvoiceItemRepository) Create(context.Context, []*domain.InvoiceItem) error {
	panic("porttest: InvoiceItemRepository.Create is not implemented")
}

func (UnimplementedInvoiceItemRepository) ListByInvoiceID(context.Context, uuid.UUID) ([]domain.InvoiceItem, error) {
	panic("porttest: InvoiceItemRepository.ListByInvoiceID is not implemented")
}

// UnimplementedInvoiceRepository panics on every InvoiceRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedInvoiceRepository struct{}

var _ port.InvoiceRepository = UnimplementedInvoiceRepository{}

func (UnimplementedInvoiceRepository) SumUnscheduledDeferral(context.Context, uuid.UUID) (int64, error) {
	panic("porttest: InvoiceRepository.SumUnscheduledDeferral is not implemented")
}

func (UnimplementedInvoiceRepository) Create(context.Context, *domain.Invoice) error {
	panic("porttest: InvoiceRepository.Create is not implemented")
}

func (UnimplementedInvoiceRepository) GetByID(context.Context, uuid.UUID) (*domain.Invoice, error) {
	panic("porttest: InvoiceRepository.GetByID is not implemented")
}

func (UnimplementedInvoiceRepository) GetByIDPublic(context.Context, uuid.UUID) (*domain.Invoice, error) {
	panic("porttest: InvoiceRepository.GetByIDPublic is not implemented")
}

func (UnimplementedInvoiceRepository) GetByCustomerID(context.Context, uuid.UUID) ([]*domain.Invoice, error) {
	panic("porttest: InvoiceRepository.GetByCustomerID is not implemented")
}

func (UnimplementedInvoiceRepository) GetByCustomerIDPaged(context.Context, uuid.UUID, int, int) ([]*domain.Invoice, error) {
	panic("porttest: InvoiceRepository.GetByCustomerIDPaged is not implemented")
}

func (UnimplementedInvoiceRepository) List(context.Context, uuid.UUID) ([]*domain.Invoice, error) {
	panic("porttest: InvoiceRepository.List is not implemented")
}

func (UnimplementedInvoiceRepository) ListPaginated(context.Context, uuid.UUID, int, int) ([]*domain.Invoice, error) {
	panic("porttest: InvoiceRepository.ListPaginated is not implemented")
}

func (UnimplementedInvoiceRepository) CountByTenant(context.Context, uuid.UUID) (int, error) {
	panic("porttest: InvoiceRepository.CountByTenant is not implemented")
}

func (UnimplementedInvoiceRepository) SearchPaginated(context.Context, uuid.UUID, string, int, int) ([]*domain.Invoice, error) {
	panic("porttest: InvoiceRepository.SearchPaginated is not implemented")
}

func (UnimplementedInvoiceRepository) CountSearch(context.Context, uuid.UUID, string) (int, error) {
	panic("porttest: InvoiceRepository.CountSearch is not implemented")
}

func (UnimplementedInvoiceRepository) ListByCustomerPaginated(context.Context, uuid.UUID, uuid.UUID, int, int) ([]*domain.Invoice, error) {
	panic("porttest: InvoiceRepository.ListByCustomerPaginated is not implemented")
}

func (UnimplementedInvoiceRepository) CountByCustomer(context.Context, uuid.UUID, uuid.UUID) (int, error) {
	panic("porttest: InvoiceRepository.CountByCustomer is not implemented")
}

func (UnimplementedInvoiceRepository) ListBySubscriptionPaginated(context.Context, uuid.UUID, uuid.UUID, int, int) ([]*domain.Invoice, error) {
	panic("porttest: InvoiceRepository.ListBySubscriptionPaginated is not implemented")
}

func (UnimplementedInvoiceRepository) CountBySubscription(context.Context, uuid.UUID, uuid.UUID) (int, error) {
	panic("porttest: InvoiceRepository.CountBySubscription is not implemented")
}

func (UnimplementedInvoiceRepository) Update(context.Context, *domain.Invoice) error {
	panic("porttest: InvoiceRepository.Update is not implemented")
}

func (UnimplementedInvoiceRepository) MarkPaid(context.Context, uuid.UUID, uuid.UUID, time.Time) (bool, error) {
	panic("porttest: InvoiceRepository.MarkPaid is not implemented")
}

func (UnimplementedInvoiceRepository) ReverseToUnpaid(context.Context, uuid.UUID, uuid.UUID, int64) (bool, error) {
	panic("porttest: InvoiceRepository.ReverseToUnpaid is not implemented")
}

func (UnimplementedInvoiceRepository) VoidIfOpen(context.Context, uuid.UUID, uuid.UUID) (bool, error) {
	panic("porttest: InvoiceRepository.VoidIfOpen is not implemented")
}

func (UnimplementedInvoiceRepository) ListCollectionsQueue(context.Context, uuid.UUID, domain.CollectionsQueueFilter) ([]domain.CollectionsQueueItem, error) {
	panic("porttest: InvoiceRepository.ListCollectionsQueue is not implemented")
}

func (UnimplementedInvoiceRepository) CountCollectionsQueue(context.Context, uuid.UUID, domain.CollectionsQueueFilter) (int, error) {
	panic("porttest: InvoiceRepository.CountCollectionsQueue is not implemented")
}

func (UnimplementedInvoiceRepository) GetCollectionsAtRisk(context.Context, uuid.UUID) ([]domain.CollectionsAtRiskRow, error) {
	panic("porttest: InvoiceRepository.GetCollectionsAtRisk is not implemented")
}

func (UnimplementedInvoiceRepository) GetCollectionsFailureBreakdown(context.Context, uuid.UUID) ([]domain.CollectionsFailureRow, error) {
	panic("porttest: InvoiceRepository.GetCollectionsFailureBreakdown is not implemented")
}

func (UnimplementedInvoiceRepository) GetOutstandingByEntity(context.Context, uuid.UUID) ([]domain.EntityOutstandingRow, error) {
	panic("porttest: InvoiceRepository.GetOutstandingByEntity is not implemented")
}

func (UnimplementedInvoiceRepository) GetCustomerFinancialSummary(context.Context, uuid.UUID, uuid.UUID) ([]domain.CustomerFinancialSummaryCurrency, error) {
	panic("porttest: InvoiceRepository.GetCustomerFinancialSummary is not implemented")
}

func (UnimplementedInvoiceRepository) GetSubscriptionFinancialSummary(context.Context, uuid.UUID, uuid.UUID) ([]domain.CustomerFinancialSummaryCurrency, error) {
	panic("porttest: InvoiceRepository.GetSubscriptionFinancialSummary is not implemented")
}

func (UnimplementedInvoiceRepository) CountUncollectibleSince(context.Context, uuid.UUID, time.Time) (int, error) {
	panic("porttest: InvoiceRepository.CountUncollectibleSince is not implemented")
}

func (UnimplementedInvoiceRepository) GetRetryEligibility(context.Context, uuid.UUID, uuid.UUID) (domain.InvoiceRetryEligibility, error) {
	panic("porttest: InvoiceRepository.GetRetryEligibility is not implemented")
}

func (UnimplementedInvoiceRepository) RequeueForRetry(context.Context, uuid.UUID, uuid.UUID) (bool, error) {
	panic("porttest: InvoiceRepository.RequeueForRetry is not implemented")
}

func (UnimplementedInvoiceRepository) SetDunningPaused(context.Context, uuid.UUID, uuid.UUID, bool) (bool, error) {
	panic("porttest: InvoiceRepository.SetDunningPaused is not implemented")
}

func (UnimplementedInvoiceRepository) MarkUncollectibleScoped(context.Context, uuid.UUID, uuid.UUID) (bool, error) {
	panic("porttest: InvoiceRepository.MarkUncollectibleScoped is not implemented")
}

func (UnimplementedInvoiceRepository) ClaimDueForRetry(context.Context, time.Duration, int) ([]*domain.Invoice, error) {
	panic("porttest: InvoiceRepository.ClaimDueForRetry is not implemented")
}

func (UnimplementedInvoiceRepository) UpdateRetryInfo(context.Context, uuid.UUID, time.Time, int) error {
	panic("porttest: InvoiceRepository.UpdateRetryInfo is not implemented")
}

func (UnimplementedInvoiceRepository) UpdateRetryInfoWithDunning(context.Context, uuid.UUID, time.Time, int, string) error {
	panic("porttest: InvoiceRepository.UpdateRetryInfoWithDunning is not implemented")
}

func (UnimplementedInvoiceRepository) MarkAsUncollectible(context.Context, uuid.UUID) error {
	panic("porttest: InvoiceRepository.MarkAsUncollectible is not implemented")
}

func (UnimplementedInvoiceRepository) SetGatewayPaymentID(context.Context, uuid.UUID, uuid.UUID, string) error {
	panic("porttest: InvoiceRepository.SetGatewayPaymentID is not implemented")
}

func (UnimplementedInvoiceRepository) GetOverdueInvoices(context.Context) ([]domain.OverdueInvoice, error) {
	panic("porttest: InvoiceRepository.GetOverdueInvoices is not implemented")
}

func (UnimplementedInvoiceRepository) ClaimOverdueForDunning(context.Context, time.Duration, int) ([]domain.OverdueInvoice, error) {
	panic("porttest: InvoiceRepository.ClaimOverdueForDunning is not implemented")
}

func (UnimplementedInvoiceRepository) GetFailedEInvoices(context.Context) ([]*domain.Invoice, error) {
	panic("porttest: InvoiceRepository.GetFailedEInvoices is not implemented")
}

func (UnimplementedInvoiceRepository) ClaimFailedEInvoices(context.Context, time.Time, time.Time, int) ([]*domain.Invoice, error) {
	panic("porttest: InvoiceRepository.ClaimFailedEInvoices is not implemented")
}

func (UnimplementedInvoiceRepository) UpdateEInvoiceStatus(context.Context, uuid.UUID, uuid.UUID, string, string, string, string, string, string) error {
	panic("porttest: InvoiceRepository.UpdateEInvoiceStatus is not implemented")
}

// UnimplementedLLMProvider panics on every LLMProvider method; embed it and override the
// methods the code under test actually calls.
type UnimplementedLLMProvider struct{}

var _ port.LLMProvider = UnimplementedLLMProvider{}

func (UnimplementedLLMProvider) GenerateCompletion(context.Context, string, string) (string, error) {
	panic("porttest: LLMProvider.GenerateCompletion is not implemented")
}

// UnimplementedLedgerRepository panics on every LedgerRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedLedgerRepository struct{}

var _ port.LedgerRepository = UnimplementedLedgerRepository{}

func (UnimplementedLedgerRepository) CreateAccount(context.Context, *domain.LedgerAccount) error {
	panic("porttest: LedgerRepository.CreateAccount is not implemented")
}

func (UnimplementedLedgerRepository) GetAccountsByTenant(context.Context, uuid.UUID, int, int) ([]*domain.LedgerAccount, error) {
	panic("porttest: LedgerRepository.GetAccountsByTenant is not implemented")
}

func (UnimplementedLedgerRepository) GetAccountByTenantAndCode(context.Context, uuid.UUID, int) (*domain.LedgerAccount, error) {
	panic("porttest: LedgerRepository.GetAccountByTenantAndCode is not implemented")
}

func (UnimplementedLedgerRepository) GetAccountByEntityAndCode(context.Context, uuid.UUID, uuid.UUID, int) (*domain.LedgerAccount, error) {
	panic("porttest: LedgerRepository.GetAccountByEntityAndCode is not implemented")
}

func (UnimplementedLedgerRepository) CreateTransaction(context.Context, *domain.LedgerTransaction) error {
	panic("porttest: LedgerRepository.CreateTransaction is not implemented")
}

func (UnimplementedLedgerRepository) CreateTransactions(context.Context, []*domain.LedgerTransaction) error {
	panic("porttest: LedgerRepository.CreateTransactions is not implemented")
}

func (UnimplementedLedgerRepository) CountTransactionsByReferenceAndCode(context.Context, uuid.UUID, uint16) (int, error) {
	panic("porttest: LedgerRepository.CountTransactionsByReferenceAndCode is not implemented")
}

func (UnimplementedLedgerRepository) GetLatestTransactionByReferenceAndCode(context.Context, uuid.UUID, uint16) (*domain.LedgerTransaction, error) {
	panic("porttest: LedgerRepository.GetLatestTransactionByReferenceAndCode is not implemented")
}

func (UnimplementedLedgerRepository) GetTransactionsByAccount(context.Context, uuid.UUID, uuid.UUID, uint16, int, int) ([]*domain.LedgerTransaction, error) {
	panic("porttest: LedgerRepository.GetTransactionsByAccount is not implemented")
}

func (UnimplementedLedgerRepository) GetTrialBalanceLines(context.Context, uuid.UUID, *int) ([]domain.TrialBalanceLine, error) {
	panic("porttest: LedgerRepository.GetTrialBalanceLines is not implemented")
}

func (UnimplementedLedgerRepository) GetGeneralLedgerRows(context.Context, uuid.UUID, *int, *time.Time, *time.Time) ([]domain.GeneralLedgerRow, error) {
	panic("porttest: LedgerRepository.GetGeneralLedgerRows is not implemented")
}

func (UnimplementedLedgerRepository) GetJournalEntriesByReference(context.Context, uuid.UUID, uuid.UUID) ([]domain.GeneralLedgerRow, error) {
	panic("porttest: LedgerRepository.GetJournalEntriesByReference is not implemented")
}

func (UnimplementedLedgerRepository) GetTransactionByID(context.Context, uuid.UUID, uuid.UUID) (*domain.GeneralLedgerRow, error) {
	panic("porttest: LedgerRepository.GetTransactionByID is not implemented")
}

func (UnimplementedLedgerRepository) GetDeferredRollforward(context.Context, uuid.UUID, time.Time, time.Time) (int64, int64, int64, error) {
	panic("porttest: LedgerRepository.GetDeferredRollforward is not implemented")
}

// UnimplementedLocker panics on every Locker method; embed it and override the
// methods the code under test actually calls.
type UnimplementedLocker struct{}

var _ port.Locker = UnimplementedLocker{}

func (UnimplementedLocker) Obtain(context.Context, string, time.Duration) (func(context.Context) error, bool, error) {
	panic("porttest: Locker.Obtain is not implemented")
}

// UnimplementedMFABackupCodeRepository panics on every MFABackupCodeRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedMFABackupCodeRepository struct{}

var _ port.MFABackupCodeRepository = UnimplementedMFABackupCodeRepository{}

func (UnimplementedMFABackupCodeRepository) CreateMany(context.Context, []*domain.MFABackupCode) error {
	panic("porttest: MFABackupCodeRepository.CreateMany is not implemented")
}

func (UnimplementedMFABackupCodeRepository) ListByUser(context.Context, uuid.UUID) ([]*domain.MFABackupCode, error) {
	panic("porttest: MFABackupCodeRepository.ListByUser is not implemented")
}

func (UnimplementedMFABackupCodeRepository) MarkUsed(context.Context, uuid.UUID) (bool, error) {
	panic("porttest: MFABackupCodeRepository.MarkUsed is not implemented")
}

func (UnimplementedMFABackupCodeRepository) DeleteByUser(context.Context, uuid.UUID) error {
	panic("porttest: MFABackupCodeRepository.DeleteByUser is not implemented")
}

// UnimplementedMFALoginTokenRepository panics on every MFALoginTokenRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedMFALoginTokenRepository struct{}

var _ port.MFALoginTokenRepository = UnimplementedMFALoginTokenRepository{}

func (UnimplementedMFALoginTokenRepository) Create(context.Context, *domain.MFALoginToken) error {
	panic("porttest: MFALoginTokenRepository.Create is not implemented")
}

func (UnimplementedMFALoginTokenRepository) GetByTokenHash(context.Context, string) (*domain.MFALoginToken, error) {
	panic("porttest: MFALoginTokenRepository.GetByTokenHash is not implemented")
}

func (UnimplementedMFALoginTokenRepository) MarkUsed(context.Context, uuid.UUID) (bool, error) {
	panic("porttest: MFALoginTokenRepository.MarkUsed is not implemented")
}

// UnimplementedMagicLinkRepository panics on every MagicLinkRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedMagicLinkRepository struct{}

var _ port.MagicLinkRepository = UnimplementedMagicLinkRepository{}

func (UnimplementedMagicLinkRepository) Create(context.Context, *domain.MagicLink) error {
	panic("porttest: MagicLinkRepository.Create is not implemented")
}

func (UnimplementedMagicLinkRepository) GetByToken(context.Context, string) (*domain.MagicLink, error) {
	panic("porttest: MagicLinkRepository.GetByToken is not implemented")
}

func (UnimplementedMagicLinkRepository) MarkUsed(context.Context, uuid.UUID) (bool, error) {
	panic("porttest: MagicLinkRepository.MarkUsed is not implemented")
}

func (UnimplementedMagicLinkRepository) DeleteExpired(context.Context) error {
	panic("porttest: MagicLinkRepository.DeleteExpired is not implemented")
}

// UnimplementedMandateRepository panics on every MandateRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedMandateRepository struct{}

var _ port.MandateRepository = UnimplementedMandateRepository{}

func (UnimplementedMandateRepository) Create(context.Context, *domain.Mandate) error {
	panic("porttest: MandateRepository.Create is not implemented")
}

func (UnimplementedMandateRepository) GetByID(context.Context, uuid.UUID, uuid.UUID) (*domain.Mandate, error) {
	panic("porttest: MandateRepository.GetByID is not implemented")
}

func (UnimplementedMandateRepository) List(context.Context, uuid.UUID, int, int) ([]*domain.Mandate, error) {
	panic("porttest: MandateRepository.List is not implemented")
}

func (UnimplementedMandateRepository) Update(context.Context, *domain.Mandate) error {
	panic("porttest: MandateRepository.Update is not implemented")
}

func (UnimplementedMandateRepository) GetByRazorpayTokenID(context.Context, string) (*domain.Mandate, error) {
	panic("porttest: MandateRepository.GetByRazorpayTokenID is not implemented")
}

func (UnimplementedMandateRepository) GetDueForPreNotification(context.Context) ([]*domain.Mandate, error) {
	panic("porttest: MandateRepository.GetDueForPreNotification is not implemented")
}

func (UnimplementedMandateRepository) GetReadyForDebit(context.Context) ([]*domain.Mandate, error) {
	panic("porttest: MandateRepository.GetReadyForDebit is not implemented")
}

func (UnimplementedMandateRepository) ClaimDueForDebit(context.Context, time.Duration) ([]*domain.Mandate, error) {
	panic("porttest: MandateRepository.ClaimDueForDebit is not implemented")
}

// UnimplementedNotifier panics on every Notifier method; embed it and override the
// methods the code under test actually calls.
type UnimplementedNotifier struct{}

var _ port.Notifier = UnimplementedNotifier{}

func (UnimplementedNotifier) SendEmail(context.Context, string, string, string) error {
	panic("porttest: Notifier.SendEmail is not implemented")
}

// UnimplementedOAuthIdentityRepository panics on every OAuthIdentityRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedOAuthIdentityRepository struct{}

var _ port.OAuthIdentityRepository = UnimplementedOAuthIdentityRepository{}

func (UnimplementedOAuthIdentityRepository) Create(context.Context, *domain.OAuthIdentity) error {
	panic("porttest: OAuthIdentityRepository.Create is not implemented")
}

func (UnimplementedOAuthIdentityRepository) GetByProviderUserID(context.Context, string, string) (*domain.OAuthIdentity, error) {
	panic("porttest: OAuthIdentityRepository.GetByProviderUserID is not implemented")
}

func (UnimplementedOAuthIdentityRepository) ListByUser(context.Context, uuid.UUID) ([]*domain.OAuthIdentity, error) {
	panic("porttest: OAuthIdentityRepository.ListByUser is not implemented")
}

// UnimplementedOfflinePaymentRepository panics on every OfflinePaymentRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedOfflinePaymentRepository struct{}

var _ port.OfflinePaymentRepository = UnimplementedOfflinePaymentRepository{}

func (UnimplementedOfflinePaymentRepository) CreateVirtualAccount(context.Context, *domain.VirtualAccount) error {
	panic("porttest: OfflinePaymentRepository.CreateVirtualAccount is not implemented")
}

func (UnimplementedOfflinePaymentRepository) GetVirtualAccountByID(context.Context, uuid.UUID) (*domain.VirtualAccount, error) {
	panic("porttest: OfflinePaymentRepository.GetVirtualAccountByID is not implemented")
}

func (UnimplementedOfflinePaymentRepository) GetVirtualAccountByRazorpayID(context.Context, string) (*domain.VirtualAccount, error) {
	panic("porttest: OfflinePaymentRepository.GetVirtualAccountByRazorpayID is not implemented")
}

func (UnimplementedOfflinePaymentRepository) ListVirtualAccounts(context.Context, uuid.UUID, int, int) ([]*domain.VirtualAccount, error) {
	panic("porttest: OfflinePaymentRepository.ListVirtualAccounts is not implemented")
}

func (UnimplementedOfflinePaymentRepository) UpdateVirtualAccount(context.Context, *domain.VirtualAccount) error {
	panic("porttest: OfflinePaymentRepository.UpdateVirtualAccount is not implemented")
}

func (UnimplementedOfflinePaymentRepository) IncrementAmountReceived(context.Context, string, int64, uuid.UUID) (*domain.VirtualAccount, error) {
	panic("porttest: OfflinePaymentRepository.IncrementAmountReceived is not implemented")
}

func (UnimplementedOfflinePaymentRepository) CreateOfflinePayment(context.Context, *domain.OfflinePayment) error {
	panic("porttest: OfflinePaymentRepository.CreateOfflinePayment is not implemented")
}

func (UnimplementedOfflinePaymentRepository) ListOfflinePayments(context.Context, uuid.UUID, int, int) ([]*domain.OfflinePayment, error) {
	panic("porttest: OfflinePaymentRepository.ListOfflinePayments is not implemented")
}

// UnimplementedOrganizationRepository panics on every OrganizationRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedOrganizationRepository struct{}

var _ port.OrganizationRepository = UnimplementedOrganizationRepository{}

func (UnimplementedOrganizationRepository) Create(context.Context, *domain.Organization) error {
	panic("porttest: OrganizationRepository.Create is not implemented")
}

func (UnimplementedOrganizationRepository) GetByID(context.Context, uuid.UUID) (*domain.Organization, error) {
	panic("porttest: OrganizationRepository.GetByID is not implemented")
}

func (UnimplementedOrganizationRepository) Update(context.Context, *domain.Organization) error {
	panic("porttest: OrganizationRepository.Update is not implemented")
}

func (UnimplementedOrganizationRepository) Delete(context.Context, uuid.UUID) error {
	panic("porttest: OrganizationRepository.Delete is not implemented")
}

func (UnimplementedOrganizationRepository) ListByOwner(context.Context, uuid.UUID) ([]*domain.Organization, error) {
	panic("porttest: OrganizationRepository.ListByOwner is not implemented")
}

func (UnimplementedOrganizationRepository) AddTenant(context.Context, uuid.UUID, uuid.UUID) error {
	panic("porttest: OrganizationRepository.AddTenant is not implemented")
}

func (UnimplementedOrganizationRepository) RemoveTenant(context.Context, uuid.UUID, uuid.UUID) error {
	panic("porttest: OrganizationRepository.RemoveTenant is not implemented")
}

func (UnimplementedOrganizationRepository) ListTenants(context.Context, uuid.UUID) ([]*domain.Tenant, error) {
	panic("porttest: OrganizationRepository.ListTenants is not implemented")
}

// UnimplementedPasswordResetRepository panics on every PasswordResetRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedPasswordResetRepository struct{}

var _ port.PasswordResetRepository = UnimplementedPasswordResetRepository{}

func (UnimplementedPasswordResetRepository) Create(context.Context, *domain.PasswordResetToken) error {
	panic("porttest: PasswordResetRepository.Create is not implemented")
}

func (UnimplementedPasswordResetRepository) GetByTokenHash(context.Context, string) (*domain.PasswordResetToken, error) {
	panic("porttest: PasswordResetRepository.GetByTokenHash is not implemented")
}

func (UnimplementedPasswordResetRepository) MarkUsed(context.Context, uuid.UUID) (bool, error) {
	panic("porttest: PasswordResetRepository.MarkUsed is not implemented")
}

// UnimplementedPaymentGateway panics on every PaymentGateway method; embed it and override the
// methods the code under test actually calls.
type UnimplementedPaymentGateway struct{}

var _ port.PaymentGateway = UnimplementedPaymentGateway{}

func (UnimplementedPaymentGateway) CreateOrder(context.Context, int64, string, string, string) (*port.PaymentOrder, error) {
	panic("porttest: PaymentGateway.CreateOrder is not implemented")
}

func (UnimplementedPaymentGateway) VerifyPayment(context.Context, string, string, string) error {
	panic("porttest: PaymentGateway.VerifyPayment is not implemented")
}

func (UnimplementedPaymentGateway) CreateSubscription(context.Context, string, int, string, *int64, string) (string, error) {
	panic("porttest: PaymentGateway.CreateSubscription is not implemented")
}

func (UnimplementedPaymentGateway) RetryPayment(context.Context, string, int64, string) (*port.PaymentResult, error) {
	panic("porttest: PaymentGateway.RetryPayment is not implemented")
}

func (UnimplementedPaymentGateway) CreateMandate(context.Context, string, string, string, int64, string, string) (*port.MandateResult, error) {
	panic("porttest: PaymentGateway.CreateMandate is not implemented")
}

func (UnimplementedPaymentGateway) ExecuteMandateDebit(context.Context, port.MandateDebitRequest) (*port.PaymentResult, error) {
	panic("porttest: PaymentGateway.ExecuteMandateDebit is not implemented")
}

func (UnimplementedPaymentGateway) RevokeMandate(context.Context, string, string, string) error {
	panic("porttest: PaymentGateway.RevokeMandate is not implemented")
}

func (UnimplementedPaymentGateway) CreateVirtualAccount(context.Context, string, string, int64, string) (*port.VirtualAccountResult, error) {
	panic("porttest: PaymentGateway.CreateVirtualAccount is not implemented")
}

func (UnimplementedPaymentGateway) CancelSubscription(context.Context, string) error {
	panic("porttest: PaymentGateway.CancelSubscription is not implemented")
}

func (UnimplementedPaymentGateway) Refund(context.Context, string, int64, string) (*port.RefundResult, error) {
	panic("porttest: PaymentGateway.Refund is not implemented")
}

// UnimplementedPlanRepository panics on every PlanRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedPlanRepository struct{}

var _ port.PlanRepository = UnimplementedPlanRepository{}

func (UnimplementedPlanRepository) Create(context.Context, *domain.Plan) error {
	panic("porttest: PlanRepository.Create is not implemented")
}

func (UnimplementedPlanRepository) GetByID(context.Context, uuid.UUID) (*domain.Plan, error) {
	panic("porttest: PlanRepository.GetByID is not implemented")
}

func (UnimplementedPlanRepository) GetByCode(context.Context, uuid.UUID, string) (*domain.Plan, error) {
	panic("porttest: PlanRepository.GetByCode is not implemented")
}

func (UnimplementedPlanRepository) List(context.Context, uuid.UUID, domain.PlanFilter) ([]*domain.Plan, error) {
	panic("porttest: PlanRepository.List is not implemented")
}

func (UnimplementedPlanRepository) Update(context.Context, *domain.Plan) error {
	panic("porttest: PlanRepository.Update is not implemented")
}

// UnimplementedPortalSessionRepository panics on every PortalSessionRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedPortalSessionRepository struct{}

var _ port.PortalSessionRepository = UnimplementedPortalSessionRepository{}

func (UnimplementedPortalSessionRepository) Create(context.Context, *domain.PortalSession) error {
	panic("porttest: PortalSessionRepository.Create is not implemented")
}

func (UnimplementedPortalSessionRepository) GetByToken(context.Context, string) (*domain.PortalSession, error) {
	panic("porttest: PortalSessionRepository.GetByToken is not implemented")
}

func (UnimplementedPortalSessionRepository) Delete(context.Context, uuid.UUID) error {
	panic("porttest: PortalSessionRepository.Delete is not implemented")
}

func (UnimplementedPortalSessionRepository) DeleteExpired(context.Context) error {
	panic("porttest: PortalSessionRepository.DeleteExpired is not implemented")
}

// UnimplementedProgressiveBillingRepository panics on every ProgressiveBillingRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedProgressiveBillingRepository struct{}

var _ port.ProgressiveBillingRepository = UnimplementedProgressiveBillingRepository{}

func (UnimplementedProgressiveBillingRepository) GetThreshold(context.Context, uuid.UUID) (*int64, error) {
	panic("porttest: ProgressiveBillingRepository.GetThreshold is not implemented")
}

func (UnimplementedProgressiveBillingRepository) ListActiveProgressiveSubscriptionIDs(context.Context) ([]uuid.UUID, error) {
	panic("porttest: ProgressiveBillingRepository.ListActiveProgressiveSubscriptionIDs is not implemented")
}

func (UnimplementedProgressiveBillingRepository) GetWatermark(context.Context, uuid.UUID, uuid.UUID, time.Time) (int64, error) {
	panic("porttest: ProgressiveBillingRepository.GetWatermark is not implemented")
}

func (UnimplementedProgressiveBillingRepository) AdvanceWatermarkCAS(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, time.Time, int64, int64) (bool, error) {
	panic("porttest: ProgressiveBillingRepository.AdvanceWatermarkCAS is not implemented")
}

// UnimplementedQuoteRepository panics on every QuoteRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedQuoteRepository struct{}

var _ port.QuoteRepository = UnimplementedQuoteRepository{}

func (UnimplementedQuoteRepository) Create(context.Context, *domain.Quote) error {
	panic("porttest: QuoteRepository.Create is not implemented")
}

func (UnimplementedQuoteRepository) GetByID(context.Context, uuid.UUID, uuid.UUID) (*domain.Quote, error) {
	panic("porttest: QuoteRepository.GetByID is not implemented")
}

func (UnimplementedQuoteRepository) Update(context.Context, *domain.Quote) error {
	panic("porttest: QuoteRepository.Update is not implemented")
}

func (UnimplementedQuoteRepository) Delete(context.Context, uuid.UUID, uuid.UUID) error {
	panic("porttest: QuoteRepository.Delete is not implemented")
}

func (UnimplementedQuoteRepository) List(context.Context, uuid.UUID, domain.QuoteFilter) ([]*domain.Quote, error) {
	panic("porttest: QuoteRepository.List is not implemented")
}

func (UnimplementedQuoteRepository) GetNextQuoteNumber(context.Context, uuid.UUID) (string, error) {
	panic("porttest: QuoteRepository.GetNextQuoteNumber is not implemented")
}

func (UnimplementedQuoteRepository) ClaimForConversion(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (bool, error) {
	panic("porttest: QuoteRepository.ClaimForConversion is not implemented")
}

func (UnimplementedQuoteRepository) ReleaseConversion(context.Context, uuid.UUID, uuid.UUID) error {
	panic("porttest: QuoteRepository.ReleaseConversion is not implemented")
}

// UnimplementedRateMetadataProvider panics on every RateMetadataProvider method; embed it and override the
// methods the code under test actually calls.
type UnimplementedRateMetadataProvider struct{}

var _ port.RateMetadataProvider = UnimplementedRateMetadataProvider{}

func (UnimplementedRateMetadataProvider) RateMetadata() port.RateMetadata {
	panic("porttest: RateMetadataProvider.RateMetadata is not implemented")
}

// UnimplementedReferralRepository panics on every ReferralRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedReferralRepository struct{}

var _ port.ReferralRepository = UnimplementedReferralRepository{}

func (UnimplementedReferralRepository) Create(context.Context, *domain.Referral) error {
	panic("porttest: ReferralRepository.Create is not implemented")
}

func (UnimplementedReferralRepository) GetByID(context.Context, uuid.UUID, uuid.UUID) (*domain.Referral, error) {
	panic("porttest: ReferralRepository.GetByID is not implemented")
}

func (UnimplementedReferralRepository) GetByCode(context.Context, uuid.UUID, string) (*domain.Referral, error) {
	panic("porttest: ReferralRepository.GetByCode is not implemented")
}

func (UnimplementedReferralRepository) GetByReferrerID(context.Context, uuid.UUID, uuid.UUID) ([]*domain.Referral, error) {
	panic("porttest: ReferralRepository.GetByReferrerID is not implemented")
}

func (UnimplementedReferralRepository) GetByReferredID(context.Context, uuid.UUID, uuid.UUID) (*domain.Referral, error) {
	panic("porttest: ReferralRepository.GetByReferredID is not implemented")
}

func (UnimplementedReferralRepository) List(context.Context, uuid.UUID, int, int) ([]*domain.Referral, error) {
	panic("porttest: ReferralRepository.List is not implemented")
}

func (UnimplementedReferralRepository) Update(context.Context, *domain.Referral) error {
	panic("porttest: ReferralRepository.Update is not implemented")
}

// UnimplementedSMSSender panics on every SMSSender method; embed it and override the
// methods the code under test actually calls.
type UnimplementedSMSSender struct{}

var _ port.SMSSender = UnimplementedSMSSender{}

func (UnimplementedSMSSender) Send(context.Context, port.SMSMessage) error {
	panic("porttest: SMSSender.Send is not implemented")
}

// UnimplementedSSOAssertionReplayStore panics on every SSOAssertionReplayStore method; embed it and override the
// methods the code under test actually calls.
type UnimplementedSSOAssertionReplayStore struct{}

var _ port.SSOAssertionReplayStore = UnimplementedSSOAssertionReplayStore{}

func (UnimplementedSSOAssertionReplayStore) MarkConsumed(context.Context, uuid.UUID, string, time.Time) error {
	panic("porttest: SSOAssertionReplayStore.MarkConsumed is not implemented")
}

// UnimplementedSSOConnectionRepository panics on every SSOConnectionRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedSSOConnectionRepository struct{}

var _ port.SSOConnectionRepository = UnimplementedSSOConnectionRepository{}

func (UnimplementedSSOConnectionRepository) GetByTenant(context.Context, uuid.UUID) (*domain.SSOConnection, error) {
	panic("porttest: SSOConnectionRepository.GetByTenant is not implemented")
}

func (UnimplementedSSOConnectionRepository) Upsert(context.Context, *domain.SSOConnection) error {
	panic("porttest: SSOConnectionRepository.Upsert is not implemented")
}

func (UnimplementedSSOConnectionRepository) Delete(context.Context, uuid.UUID) error {
	panic("porttest: SSOConnectionRepository.Delete is not implemented")
}

// UnimplementedSessionRepository panics on every SessionRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedSessionRepository struct{}

var _ port.SessionRepository = UnimplementedSessionRepository{}

func (UnimplementedSessionRepository) Create(context.Context, *domain.Session) error {
	panic("porttest: SessionRepository.Create is not implemented")
}

func (UnimplementedSessionRepository) GetByTokenHash(context.Context, string) (*domain.Session, error) {
	panic("porttest: SessionRepository.GetByTokenHash is not implemented")
}

func (UnimplementedSessionRepository) GetByID(context.Context, uuid.UUID) (*domain.Session, error) {
	panic("porttest: SessionRepository.GetByID is not implemented")
}

func (UnimplementedSessionRepository) ListByUser(context.Context, uuid.UUID) ([]*domain.Session, error) {
	panic("porttest: SessionRepository.ListByUser is not implemented")
}

func (UnimplementedSessionRepository) DeleteByTokenHash(context.Context, string) error {
	panic("porttest: SessionRepository.DeleteByTokenHash is not implemented")
}

func (UnimplementedSessionRepository) DeleteByID(context.Context, uuid.UUID) error {
	panic("porttest: SessionRepository.DeleteByID is not implemented")
}

func (UnimplementedSessionRepository) DeleteByUser(context.Context, uuid.UUID) error {
	panic("porttest: SessionRepository.DeleteByUser is not implemented")
}

func (UnimplementedSessionRepository) DeleteByUserExcept(context.Context, uuid.UUID, string) error {
	panic("porttest: SessionRepository.DeleteByUserExcept is not implemented")
}

// UnimplementedSubscriptionAddonRepository panics on every SubscriptionAddonRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedSubscriptionAddonRepository struct{}

var _ port.SubscriptionAddonRepository = UnimplementedSubscriptionAddonRepository{}

func (UnimplementedSubscriptionAddonRepository) Create(context.Context, *domain.SubscriptionAddon) error {
	panic("porttest: SubscriptionAddonRepository.Create is not implemented")
}

func (UnimplementedSubscriptionAddonRepository) GetByID(context.Context, uuid.UUID, uuid.UUID) (*domain.SubscriptionAddon, error) {
	panic("porttest: SubscriptionAddonRepository.GetByID is not implemented")
}

func (UnimplementedSubscriptionAddonRepository) ListBySubscriptionID(context.Context, uuid.UUID, uuid.UUID) ([]*domain.SubscriptionAddon, error) {
	panic("porttest: SubscriptionAddonRepository.ListBySubscriptionID is not implemented")
}

func (UnimplementedSubscriptionAddonRepository) Delete(context.Context, uuid.UUID, uuid.UUID) error {
	panic("porttest: SubscriptionAddonRepository.Delete is not implemented")
}

// UnimplementedSubscriptionRepository panics on every SubscriptionRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedSubscriptionRepository struct{}

var _ port.SubscriptionRepository = UnimplementedSubscriptionRepository{}

func (UnimplementedSubscriptionRepository) Create(context.Context, *domain.Subscription) error {
	panic("porttest: SubscriptionRepository.Create is not implemented")
}

func (UnimplementedSubscriptionRepository) GetByID(context.Context, uuid.UUID) (*domain.Subscription, error) {
	panic("porttest: SubscriptionRepository.GetByID is not implemented")
}

func (UnimplementedSubscriptionRepository) GetByStripeSubscriptionID(context.Context, string) (*domain.Subscription, error) {
	panic("porttest: SubscriptionRepository.GetByStripeSubscriptionID is not implemented")
}

func (UnimplementedSubscriptionRepository) GetActiveSubscriptions(context.Context, uuid.UUID) ([]*domain.Subscription, error) {
	panic("porttest: SubscriptionRepository.GetActiveSubscriptions is not implemented")
}

func (UnimplementedSubscriptionRepository) List(context.Context, uuid.UUID, domain.SubscriptionFilter) ([]*domain.Subscription, error) {
	panic("porttest: SubscriptionRepository.List is not implemented")
}

func (UnimplementedSubscriptionRepository) Update(context.Context, *domain.Subscription) error {
	panic("porttest: SubscriptionRepository.Update is not implemented")
}

func (UnimplementedSubscriptionRepository) SetResumeAt(context.Context, uuid.UUID, uuid.UUID, *time.Time) error {
	panic("porttest: SubscriptionRepository.SetResumeAt is not implemented")
}

func (UnimplementedSubscriptionRepository) CountActiveByCustomer(context.Context, uuid.UUID) (map[uuid.UUID]int, error) {
	panic("porttest: SubscriptionRepository.CountActiveByCustomer is not implemented")
}

// UnimplementedTaxEngine panics on every TaxEngine method; embed it and override the
// methods the code under test actually calls.
type UnimplementedTaxEngine struct{}

var _ port.TaxEngine = UnimplementedTaxEngine{}

func (UnimplementedTaxEngine) CalculateTax(context.Context, *port.TaxRequest) (*port.TaxCalculation, error) {
	panic("porttest: TaxEngine.CalculateTax is not implemented")
}

func (UnimplementedTaxEngine) GetApplicableRate(context.Context, *port.TaxRequest) (float64, error) {
	panic("porttest: TaxEngine.GetApplicableRate is not implemented")
}

// UnimplementedTaxNexusRepository panics on every TaxNexusRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedTaxNexusRepository struct{}

var _ port.TaxNexusRepository = UnimplementedTaxNexusRepository{}

func (UnimplementedTaxNexusRepository) ListByTenant(context.Context, uuid.UUID) ([]domain.TaxNexus, error) {
	panic("porttest: TaxNexusRepository.ListByTenant is not implemented")
}

func (UnimplementedTaxNexusRepository) SetStates(context.Context, uuid.UUID, []domain.TaxNexus) error {
	panic("porttest: TaxNexusRepository.SetStates is not implemented")
}

func (UnimplementedTaxNexusRepository) Delete(context.Context, uuid.UUID, string) error {
	panic("porttest: TaxNexusRepository.Delete is not implemented")
}

func (UnimplementedTaxNexusRepository) NexusFor(context.Context, uuid.UUID, string) (bool, bool, error) {
	panic("porttest: TaxNexusRepository.NexusFor is not implemented")
}

// UnimplementedUnbilledChargeRepository panics on every UnbilledChargeRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedUnbilledChargeRepository struct{}

var _ port.UnbilledChargeRepository = UnimplementedUnbilledChargeRepository{}

func (UnimplementedUnbilledChargeRepository) Create(context.Context, *domain.UnbilledCharge) error {
	panic("porttest: UnbilledChargeRepository.Create is not implemented")
}

func (UnimplementedUnbilledChargeRepository) ListBySubscriptionID(context.Context, uuid.UUID) ([]*domain.UnbilledCharge, error) {
	panic("porttest: UnbilledChargeRepository.ListBySubscriptionID is not implemented")
}

func (UnimplementedUnbilledChargeRepository) ListBySubscriptionIDPaged(context.Context, uuid.UUID, int, int) ([]*domain.UnbilledCharge, error) {
	panic("porttest: UnbilledChargeRepository.ListBySubscriptionIDPaged is not implemented")
}

func (UnimplementedUnbilledChargeRepository) MarkAsInvoiced(context.Context, []uuid.UUID) error {
	panic("porttest: UnbilledChargeRepository.MarkAsInvoiced is not implemented")
}

// UnimplementedUsageAlertRepository panics on every UsageAlertRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedUsageAlertRepository struct{}

var _ port.UsageAlertRepository = UnimplementedUsageAlertRepository{}

func (UnimplementedUsageAlertRepository) Create(context.Context, *domain.UsageAlert) error {
	panic("porttest: UsageAlertRepository.Create is not implemented")
}

func (UnimplementedUsageAlertRepository) ListBySubscription(context.Context, uuid.UUID, uuid.UUID) ([]domain.UsageAlert, error) {
	panic("porttest: UsageAlertRepository.ListBySubscription is not implemented")
}

func (UnimplementedUsageAlertRepository) ListByTenant(context.Context, uuid.UUID) ([]domain.UsageAlert, error) {
	panic("porttest: UsageAlertRepository.ListByTenant is not implemented")
}

func (UnimplementedUsageAlertRepository) Delete(context.Context, uuid.UUID, uuid.UUID) error {
	panic("porttest: UsageAlertRepository.Delete is not implemented")
}

func (UnimplementedUsageAlertRepository) UpdateThreshold(context.Context, uuid.UUID, uuid.UUID, domain.UsageAlertThresholdType, int64) error {
	panic("porttest: UsageAlertRepository.UpdateThreshold is not implemented")
}

func (UnimplementedUsageAlertRepository) ListAll(context.Context, int) ([]domain.UsageAlert, error) {
	panic("porttest: UsageAlertRepository.ListAll is not implemented")
}

func (UnimplementedUsageAlertRepository) MarkFired(context.Context, uuid.UUID, time.Time) (bool, error) {
	panic("porttest: UsageAlertRepository.MarkFired is not implemented")
}

// UnimplementedUsageRatingRepository panics on every UsageRatingRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedUsageRatingRepository struct{}

var _ port.UsageRatingRepository = UnimplementedUsageRatingRepository{}

func (UnimplementedUsageRatingRepository) Create(context.Context, *domain.UsageRating) (bool, error) {
	panic("porttest: UsageRatingRepository.Create is not implemented")
}

func (UnimplementedUsageRatingRepository) Exists(context.Context, uuid.UUID, uuid.UUID, time.Time) (bool, error) {
	panic("porttest: UsageRatingRepository.Exists is not implemented")
}

// UnimplementedUsageRepository panics on every UsageRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedUsageRepository struct{}

var _ port.UsageRepository = UnimplementedUsageRepository{}

func (UnimplementedUsageRepository) RecordEvent(context.Context, *domain.UsageEvent) error {
	panic("porttest: UsageRepository.RecordEvent is not implemented")
}

func (UnimplementedUsageRepository) RecordEventIdempotent(context.Context, *domain.UsageEvent) (bool, error) {
	panic("porttest: UsageRepository.RecordEventIdempotent is not implemented")
}

func (UnimplementedUsageRepository) GetUsageForPeriod(context.Context, string, string, time.Time, time.Time) (int64, error) {
	panic("porttest: UsageRepository.GetUsageForPeriod is not implemented")
}

func (UnimplementedUsageRepository) GetUsageStats(context.Context, uuid.UUID) ([]*domain.UsageStats, error) {
	panic("porttest: UsageRepository.GetUsageStats is not implemented")
}

func (UnimplementedUsageRepository) CountMeteredCustomers(context.Context, uuid.UUID) (int64, error) {
	panic("porttest: UsageRepository.CountMeteredCustomers is not implemented")
}

func (UnimplementedUsageRepository) QueryUsage(context.Context, uuid.UUID, domain.UsageQueryFilter) ([]domain.UsageBucket, error) {
	panic("porttest: UsageRepository.QueryUsage is not implemented")
}

func (UnimplementedUsageRepository) ListRecentEvents(context.Context, uuid.UUID, *uuid.UUID, string, int, int) ([]domain.UsageEvent, error) {
	panic("porttest: UsageRepository.ListRecentEvents is not implemented")
}

func (UnimplementedUsageRepository) GetSubscriptionUsageByDimension(context.Context, uuid.UUID, uuid.UUID, time.Time, time.Time) ([]domain.SubscriptionDimensionUsage, error) {
	panic("porttest: UsageRepository.GetSubscriptionUsageByDimension is not implemented")
}

func (UnimplementedUsageRepository) ListDimensions(context.Context, uuid.UUID) ([]domain.UsageDimension, error) {
	panic("porttest: UsageRepository.ListDimensions is not implemented")
}

func (UnimplementedUsageRepository) AggregateForMetric(context.Context, uuid.UUID, domain.BillableMetric, time.Time, time.Time) (int64, error) {
	panic("porttest: UsageRepository.AggregateForMetric is not implemented")
}

func (UnimplementedUsageRepository) SumDynamicAmount(context.Context, uuid.UUID, string, time.Time, time.Time) (int64, error) {
	panic("porttest: UsageRepository.SumDynamicAmount is not implemented")
}

func (UnimplementedUsageRepository) AggregateForMetricFiltered(context.Context, uuid.UUID, domain.BillableMetric, string, []string, bool, time.Time, time.Time) (int64, error) {
	panic("porttest: UsageRepository.AggregateForMetricFiltered is not implemented")
}

func (UnimplementedUsageRepository) StreamEventsForMetric(context.Context, uuid.UUID, string, time.Time, time.Time, func(quantity int64, ts time.Time, props map[string]string) error) error {
	panic("porttest: UsageRepository.StreamEventsForMetric is not implemented")
}

func (UnimplementedUsageRepository) SumQuantityBefore(context.Context, uuid.UUID, string, time.Time) (int64, error) {
	panic("porttest: UsageRepository.SumQuantityBefore is not implemented")
}

// UnimplementedUserRepository panics on every UserRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedUserRepository struct{}

var _ port.UserRepository = UnimplementedUserRepository{}

func (UnimplementedUserRepository) Create(context.Context, *domain.User) error {
	panic("porttest: UserRepository.Create is not implemented")
}

func (UnimplementedUserRepository) GetByEmail(context.Context, string) (*domain.User, error) {
	panic("porttest: UserRepository.GetByEmail is not implemented")
}

func (UnimplementedUserRepository) ExistsByEmail(context.Context, string) (bool, error) {
	panic("porttest: UserRepository.ExistsByEmail is not implemented")
}

func (UnimplementedUserRepository) GetByID(context.Context, uuid.UUID, uuid.UUID) (*domain.User, error) {
	panic("porttest: UserRepository.GetByID is not implemented")
}

func (UnimplementedUserRepository) GetByIDGlobal(context.Context, uuid.UUID) (*domain.User, error) {
	panic("porttest: UserRepository.GetByIDGlobal is not implemented")
}

func (UnimplementedUserRepository) ListByTenant(context.Context, uuid.UUID) ([]*domain.User, error) {
	panic("porttest: UserRepository.ListByTenant is not implemented")
}

func (UnimplementedUserRepository) UpdateRole(context.Context, uuid.UUID, uuid.UUID, domain.Role) error {
	panic("porttest: UserRepository.UpdateRole is not implemented")
}

func (UnimplementedUserRepository) Delete(context.Context, uuid.UUID, uuid.UUID) error {
	panic("porttest: UserRepository.Delete is not implemented")
}

func (UnimplementedUserRepository) CountOwners(context.Context, uuid.UUID) (int, error) {
	panic("porttest: UserRepository.CountOwners is not implemented")
}

func (UnimplementedUserRepository) UpdatePassword(context.Context, uuid.UUID, string) error {
	panic("porttest: UserRepository.UpdatePassword is not implemented")
}

func (UnimplementedUserRepository) SetMFASecret(context.Context, uuid.UUID, uuid.UUID, string) error {
	panic("porttest: UserRepository.SetMFASecret is not implemented")
}

func (UnimplementedUserRepository) SetMFAEnabled(context.Context, uuid.UUID, uuid.UUID, bool) error {
	panic("porttest: UserRepository.SetMFAEnabled is not implemented")
}

func (UnimplementedUserRepository) SetMFALastTimestep(context.Context, uuid.UUID, uuid.UUID, int64) error {
	panic("porttest: UserRepository.SetMFALastTimestep is not implemented")
}

func (UnimplementedUserRepository) RegisterFailedLogin(context.Context, uuid.UUID, int, time.Duration) error {
	panic("porttest: UserRepository.RegisterFailedLogin is not implemented")
}

func (UnimplementedUserRepository) ClearFailedLogins(context.Context, uuid.UUID) error {
	panic("porttest: UserRepository.ClearFailedLogins is not implemented")
}

func (UnimplementedUserRepository) ClearMFA(context.Context, uuid.UUID, uuid.UUID) error {
	panic("porttest: UserRepository.ClearMFA is not implemented")
}

func (UnimplementedUserRepository) MarkEmailVerified(context.Context, uuid.UUID) error {
	panic("porttest: UserRepository.MarkEmailVerified is not implemented")
}

// UnimplementedWalletRepository panics on every WalletRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedWalletRepository struct{}

var _ port.WalletRepository = UnimplementedWalletRepository{}

func (UnimplementedWalletRepository) Create(context.Context, *domain.Wallet) error {
	panic("porttest: WalletRepository.Create is not implemented")
}

func (UnimplementedWalletRepository) GetByID(context.Context, uuid.UUID, uuid.UUID) (*domain.Wallet, error) {
	panic("porttest: WalletRepository.GetByID is not implemented")
}

func (UnimplementedWalletRepository) Close(context.Context, uuid.UUID, uuid.UUID, time.Time) (port.WalletCloseResult, error) {
	panic("porttest: WalletRepository.Close is not implemented")
}

func (UnimplementedWalletRepository) GetByCustomerEntityAndCurrency(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, string) (*domain.Wallet, error) {
	panic("porttest: WalletRepository.GetByCustomerEntityAndCurrency is not implemented")
}

func (UnimplementedWalletRepository) ListByCustomer(context.Context, uuid.UUID, uuid.UUID) ([]domain.Wallet, error) {
	panic("porttest: WalletRepository.ListByCustomer is not implemented")
}

func (UnimplementedWalletRepository) ListByTenant(context.Context, uuid.UUID, int) ([]domain.Wallet, error) {
	panic("porttest: WalletRepository.ListByTenant is not implemented")
}

func (UnimplementedWalletRepository) UpdateAutoRecharge(context.Context, uuid.UUID, uuid.UUID, *int64, *int64) error {
	panic("porttest: WalletRepository.UpdateAutoRecharge is not implemented")
}

func (UnimplementedWalletRepository) TopUp(context.Context, *domain.WalletTransaction) (bool, error) {
	panic("porttest: WalletRepository.TopUp is not implemented")
}

func (UnimplementedWalletRepository) Drain(context.Context, uuid.UUID, uuid.UUID, int64, uuid.UUID, time.Time) (int64, error) {
	panic("porttest: WalletRepository.Drain is not implemented")
}

func (UnimplementedWalletRepository) ExpireOverdue(context.Context, time.Time) ([]port.WalletExpiry, error) {
	panic("porttest: WalletRepository.ExpireOverdue is not implemented")
}

func (UnimplementedWalletRepository) ListDueForRecharge(context.Context, int) ([]domain.Wallet, error) {
	panic("porttest: WalletRepository.ListDueForRecharge is not implemented")
}

func (UnimplementedWalletRepository) ListTransactions(context.Context, uuid.UUID, uuid.UUID, int) ([]domain.WalletTransaction, error) {
	panic("porttest: WalletRepository.ListTransactions is not implemented")
}

// UnimplementedWebhookEndpointRepository panics on every WebhookEndpointRepository method; embed it and override the
// methods the code under test actually calls.
type UnimplementedWebhookEndpointRepository struct{}

var _ port.WebhookEndpointRepository = UnimplementedWebhookEndpointRepository{}

func (UnimplementedWebhookEndpointRepository) Create(context.Context, *domain.WebhookEndpoint) error {
	panic("porttest: WebhookEndpointRepository.Create is not implemented")
}

func (UnimplementedWebhookEndpointRepository) GetByID(context.Context, uuid.UUID) (*domain.WebhookEndpoint, error) {
	panic("porttest: WebhookEndpointRepository.GetByID is not implemented")
}

func (UnimplementedWebhookEndpointRepository) ListByTenantID(context.Context, uuid.UUID) ([]*domain.WebhookEndpoint, error) {
	panic("porttest: WebhookEndpointRepository.ListByTenantID is not implemented")
}

func (UnimplementedWebhookEndpointRepository) Delete(context.Context, uuid.UUID, uuid.UUID) error {
	panic("porttest: WebhookEndpointRepository.Delete is not implemented")
}

func (UnimplementedWebhookEndpointRepository) Update(context.Context, *domain.WebhookEndpoint) error {
	panic("porttest: WebhookEndpointRepository.Update is not implemented")
}

func (UnimplementedWebhookEndpointRepository) GetByTenantAndEventType(context.Context, uuid.UUID, string) ([]*domain.WebhookEndpoint, error) {
	panic("porttest: WebhookEndpointRepository.GetByTenantAndEventType is not implemented")
}

// allUnimplemented lists every generated type; the package test drives each
// method through it.
func allUnimplemented() []any {
	return []any{
		UnimplementedAccountingConnectionRepository{},
		UnimplementedAccountingGateway{},
		UnimplementedAccountingMappingRepository{},
		UnimplementedAccountingService{},
		UnimplementedAuditLogRepository{},
		UnimplementedBillableMetricRepository{},
		UnimplementedCancelFlowRepository{},
		UnimplementedCardVault{},
		UnimplementedChargeRepository{},
		UnimplementedCouponRepository{},
		UnimplementedCustomerRepository{},
		UnimplementedDisputeRepository{},
		UnimplementedDunningCampaignRepository{},
		UnimplementedEUInvoiceTransport{},
		UnimplementedEmailSender{},
		UnimplementedEmailVerificationRepository{},
		UnimplementedEntitlementRepository{},
		UnimplementedEventDeliveryRepository{},
		UnimplementedEventRepository{},
		UnimplementedExchangeRateProvider{},
		UnimplementedGSPAdapter{},
		UnimplementedGatewayConnectionRepository{},
		UnimplementedGiftRepository{},
		UnimplementedIdempotencyStore{},
		UnimplementedImportRefRepository{},
		UnimplementedIntegrationConnectionRepository{},
		UnimplementedInvoiceItemRepository{},
		UnimplementedInvoiceRepository{},
		UnimplementedLLMProvider{},
		UnimplementedLedgerRepository{},
		UnimplementedLocker{},
		UnimplementedMFABackupCodeRepository{},
		UnimplementedMFALoginTokenRepository{},
		UnimplementedMagicLinkRepository{},
		UnimplementedMandateRepository{},
		UnimplementedNotifier{},
		UnimplementedOAuthIdentityRepository{},
		UnimplementedOfflinePaymentRepository{},
		UnimplementedOrganizationRepository{},
		UnimplementedPasswordResetRepository{},
		UnimplementedPaymentGateway{},
		UnimplementedPlanRepository{},
		UnimplementedPortalSessionRepository{},
		UnimplementedProgressiveBillingRepository{},
		UnimplementedQuoteRepository{},
		UnimplementedRateMetadataProvider{},
		UnimplementedReferralRepository{},
		UnimplementedSMSSender{},
		UnimplementedSSOAssertionReplayStore{},
		UnimplementedSSOConnectionRepository{},
		UnimplementedSessionRepository{},
		UnimplementedSubscriptionAddonRepository{},
		UnimplementedSubscriptionRepository{},
		UnimplementedTaxEngine{},
		UnimplementedTaxNexusRepository{},
		UnimplementedUnbilledChargeRepository{},
		UnimplementedUsageAlertRepository{},
		UnimplementedUsageRatingRepository{},
		UnimplementedUsageRepository{},
		UnimplementedUserRepository{},
		UnimplementedWalletRepository{},
		UnimplementedWebhookEndpointRepository{},
	}
}
